### ISSUE TITLE
Questions about slimming AppleALC Kext

### ISSUE THREAD

**Issue by vuxuanhungg** [5T33Z0/AppleALC-Guides#6]
Hi, I'm kinda interested in slimming AppleALC kext for smaller file size. On reading your tutorial, I've got some questions:
- We only need to repeat the process of slimming the kext when a new release has fixes regarding our codec, not on every release, right? I assume that even our codec gets new layout ID, we don't need to update either. Is that right?
- At the time of me writing this, AppleALC kext version is 1.8.1. How come yours is 1.8.2 :v ?

**Comment by 5T33Z0** [comment]
- From what I know, newer releases mainly only contain new layouts. Significant changes to the kext itself are less frequent (check time timestamp of the source code). But don't quote me on that, since I am not a programmer. I usually download the latest source from time to time, replace the Resources folder by the one for my codec and I compile it again.
- I think you don't really need to update it unless there have been significant changes made to the kext to be compatible with the next version of macOS where it would crash the system otherwise (hypothetically speaking)
- My AppleALC is on 1.8.2 because that's where the current source code is at. It's usually ahead of pre-compiled binary releases

**Comment by vuxuanhungg** [comment]
Very clear, thanks for your response!
